version: "3.4"
services:
  genealogy-go:
    container_name: genealogy_go
    build:
      context: .
      dockerfile: docker/go/dev.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - genealogy-db
    volumes:
      - ".:/application"
    environment:
      CONNECTION_STRING_DB: 'MainUser:MainPassword@tcp(genealogy-db:3306)/genealogy'
  genealogy-db:
    container_name: genealogy_db
    build:
      context: .
      dockerfile: docker/mysql/dev.dockerfile
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: MainUser
      MYSQL_PASSWORD: MainPassword
networks:
  default: